fixtures:
  repositories:
    'cinder':
      repo: 'git://github.com/stackforge/puppet-cinder'
      ref: 'origin/stable/grizzly'
    'keystone':
      repo: 'git://github.com/stackforge/puppet-keystone.git'
      ref: 'origin/stable/grizzly'
    'nova':
      repo: 'git://github.com/stackforge/puppet-nova.git'
      ref: 'origin/stable/grizzly'
    'glance':
      repo: 'git://github.com/stackforge/puppet-glance.git'
      ref: 'origin/stable/grizzly'
    'horizon':
      repo: 'git://github.com/stackforge/puppet-horizon'
      ref: 'origin/stable/grizzly'
    'swift' :
      repo: 'git://github.com/stackforge/puppet-swift'
      ref: 'origin/stable/grizzly'
    'quantum':
      repo: 'git://github.com/stackforge/puppet-neutron'
      ref: 'origin/stable/grizzly'
    'ceilometer':
      repo: 'git://github.com/stackforge/puppet-ceilometer'
      ref: 'origin/stable/grizzly'
    'apt': 'git://github.com/puppetlabs/puppetlabs-apt.git'
    'apache':
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
      ref: 'origin/0.x'
    'concat': 'git://github.com/ripienaar/puppet-concat.git'
    'firewall': 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    'mysql':
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: 'origin/0.x'
    'rabbitmq':
      repo: 'git://github.com/puppetlabs/puppetlabs-rabbitmq'
      ref: 'origin/2.x'
    'memcached': 'git://github.com/saz/puppet-memcached'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'sysctl': 'git://github.com/duritong/puppet-sysctl.git'
    'inifile':  'git://github.com/puppetlabs/puppetlabs-inifile'
    'vswitch': 'git://github.com/bodepd/puppet-vswitch'
    'tempest':
      repo: 'git://github.com/stackforge/puppet-tempest'
      ref: 'origin/stable/grizzly'
    'vcsrepo': 'git://github.com/puppetlabs/puppetlabs-vcsrepo'
  symlinks:
    'openstack': "#{source_dir}"
