name    'puppetlabs-openstack'
version '0.1.0'
source  'https://github.com/puppetlabs/puppetlabs-openstack'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Openstack Module'
description 'Module to install common openstack configurations using puppet'
project_page 'https://github.com/puppetlabs/puppetlabs-openstack'

dependency 'puppetlabs/glance', '0.1.0'
dependency 'puppetlabs/horizon', '0.1.0'
dependency 'puppetlabs/keystone', '0.1.0'
dependency 'saz/memcached', '2.0.1'
dependency 'puppetlabs/msyql','0.3.0'
dependency 'puppetlabs/nova', '0.1.0'
